### PR TITLE
6 fix filtering

### LINKED ISSUE #6: fix filtering

### PR DESCRIPTION
**Pull request by benjaminbernadskiy**
fuxed filtering plus added date filtering

time for kenneth mania

### CODE REVIEW

**Comment by Constantine-nagornuk** [comment]
Seems luh calm. Kenneth will probs yell at you about the so called voids of space between code tho.

File: frontend/app/pages/index.vue [hunk 1]
```diff
@@ -127,16 +214,28 @@ const activities = [
 ];
```
Comment (Constantine-nagornuk) [inline frontend/app/pages/index.vue:214]: I added the store for this now, if I didn't do it wrong 😭

**Review by kennething — COMMENTED** [review]
good enough probably

image
